export const notes = [
    {
        id: 1,
        title: "Workspace 1 Note 1",
        body: "Eggs, Milk, Bread",
        user_id: 1,
        workspace_id: 1,
    },
    {
        id: 2,
        title: "Workspace 1 Note 2",
        body: "Green Bean Casserole, Tomatoe Soup",
        user_id: 2,
        workspace_id: 1,
    },
    {
        id: 3,
        title: "Workspace 1 Note 3",
        body: "Make this sick app",
        user_id: 3,
        workspace_id: 1,
    },
    {
        id: 4,
        title: "Workspace 2 Note 1",
        body: "Eggs, Milk, Bread",
        user_id: 1,
        workspace_id: 2,
    },
    {
        id: 5,
        title: "Workspace 2 Note 2",
        body: "Green Bean Casserole, Tomatoe Soup",
        user_id: 2,
        workspace_id: 2,
    },
    {
        id: 6,
        title: "Todo",
        body: "Workspace 2 Note 3",
        user_id: 3,
        workspace_id: 2,
    },
    {
        id: 7,
        title: "Workspace 3 Note 1",
        body: "Eggs, Milk, Bread",
        user_id: 1,
        workspace_id: 3,
    },
    {
        id: 8,
        title: "Workspace 3 Note 2",
        body: "Green Bean Casserole, Tomatoe Soup",
        user_id: 2,
        workspace_id: 3,
    },
    {
        id: 9,
        title: "Todo",
        body: "Workspace 3 Note 3",
        user_id: 3,
        workspace_id: 3,
    },
];
